import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const lessons = [
  {
    id: "lesson-2-1-1",
    moduleId: "module-2-1",
    order: 1,
    title: "Meet Nova",
    type: "STORY",
    xpReward: 100,
    gemReward: 5,
    estimatedMin: 10,
    content: {
      type: "story",
      objective: "Meet Nova and see your first Python print statement.",
      hint: "Python speaks with print(). Use it to say hello.",
      successCondition: "hasPython:print",
    },
    starterCode: { python: "print('Hello, Nova!')" },
  },
  {
    id: "lesson-2-1-2",
    moduleId: "module-2-1",
    order: 2,
    title: "Your First Python Line",
    type: "CODING",
    xpReward: 100,
    gemReward: 5,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Write a single line of Python that prints a message.",
      hint: "Start with print('your message').",
      successCondition: "hasPython:print",
    },
    starterCode: { python: "print('I can code!')" },
  },
  {
    id: "lesson-2-1-3",
    moduleId: "module-2-1",
    order: 3,
    title: "Variables are Boxes",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Store a value in a variable and print it.",
      hint: "Use name = 'Nova' then print(name).",
      successCondition: "hasPython:=",
    },
    starterCode: { python: "name = 'Nova'\\nprint(name)" },
  },
  {
    id: "lesson-2-1-4",
    moduleId: "module-2-1",
    order: 4,
    title: "String Magic",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Join two strings together with +.",
      hint: "Use + to combine text, then print it.",
      successCondition: "hasPython:+",
    },
    starterCode: { python: "greeting = 'Hello' + ' Builder'\\nprint(greeting)" },
  },
  {
    id: "lesson-2-1-5",
    moduleId: "module-2-1",
    order: 5,
    title: "Numbers and Maths",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Use +, -, and * to do math in Python.",
      hint: "Try a small sum or product, then print the result.",
      successCondition: "hasPython:+|hasPython:-|hasPython:*",
    },
    starterCode: { python: "result = 4 + 6\\nprint(result)" },
  },
  {
    id: "lesson-2-1-6",
    moduleId: "module-2-1",
    order: 6,
    title: "Ask the User",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Use input() to ask a question.",
      hint: "Store the answer from input() in a variable.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "name = input('Your name: ')\\nprint(name)" },
  },
  {
    id: "lesson-2-1-7",
    moduleId: "module-2-1",
    order: 7,
    title: "Putting it Together",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Ask a question and print a friendly response.",
      hint: "Use input() then print a greeting.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "name = input('What is your name? ')\\nprint('Hi ' + name)" },
  },
  {
    id: "lesson-2-1-8",
    moduleId: "module-2-1",
    order: 8,
    title: "The Name Game",
    type: "CHALLENGE",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "challenge",
      objective: "Build a mini greeting game with input().",
      hint: "Ask for a name and print a welcome.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "name = input('Name? ')\\nprint('Welcome, ' + name)" },
  },
  {
    id: "lesson-2-1-9",
    moduleId: "module-2-1",
    order: 9,
    title: "My First Python Program",
    type: "PROJECT",
    xpReward: 250,
    gemReward: 25,
    estimatedMin: 25,
    content: {
      type: "project",
      objective: "Create a simple program that asks and responds.",
      hint: "Combine input() and print() in your own way.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "name = input('Name? ')\\nprint('Hello, ' + name)" },
  },
  {
    id: "lesson-2-2-1",
    moduleId: "module-2-2",
    order: 1,
    title: "If This Then That",
    type: "STORY",
    xpReward: 100,
    gemReward: 5,
    estimatedMin: 10,
    content: {
      type: "story",
      objective: "Learn how Python makes decisions with if.",
      hint: "if checks a condition and runs code when it is true.",
      successCondition: "hasPython:if",
    },
    starterCode: { python: "if True:\\n    print('Yes')" },
  },
  {
    id: "lesson-2-2-2",
    moduleId: "module-2-2",
    order: 2,
    title: "Yes or No",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Write an if statement that prints a result.",
      hint: "Try if 5 > 3 then print.",
      successCondition: "hasPython:if",
    },
    starterCode: { python: "if 5 > 3:\\n    print('Yes')" },
  },
  {
    id: "lesson-2-2-3",
    moduleId: "module-2-2",
    order: 3,
    title: "Comparing Things",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Compare values using ==, >, and <.",
      hint: "Try a comparison and print the result.",
      successCondition: "hasPython:==|hasPython:>|hasPython:<",
    },
    starterCode: { python: "print(3 == 3)\\nprint(5 > 2)\\nprint(1 < 4)" },
  },
  {
    id: "lesson-2-2-4",
    moduleId: "module-2-2",
    order: 4,
    title: "Multiple Choices",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Add elif for extra choices.",
      hint: "elif sits between if and else.",
      successCondition: "hasPython:elif",
    },
    starterCode: {
      python: "score = 8\\nif score > 9:\\n    print('A')\\nelif score > 6:\\n    print('B')\\nelse:\\n    print('C')",
    },
  },
  {
    id: "lesson-2-2-5",
    moduleId: "module-2-2",
    order: 5,
    title: "The Password Game",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Check a password with if.",
      hint: "Compare the input to the correct password.",
      successCondition: "hasPython:if",
    },
    starterCode: {
      python: "password = input('Password: ')\\nif password == 'nova':\\n    print('Access granted')",
    },
  },
  {
    id: "lesson-2-2-6",
    moduleId: "module-2-2",
    order: 6,
    title: "True and False",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Use True and False in your logic.",
      hint: "Booleans are True or False.",
      successCondition: "hasPython:True|hasPython:False",
    },
    starterCode: { python: "flag = True\\nprint(flag)" },
  },
  {
    id: "lesson-2-2-7",
    moduleId: "module-2-2",
    order: 7,
    title: "The Quiz Game",
    type: "CHALLENGE",
    xpReward: 250,
    gemReward: 20,
    estimatedMin: 20,
    content: {
      type: "challenge",
      objective: "Ask a question and check the answer with if.",
      hint: "Use input() then compare the answer.",
      successCondition: "hasPython:if",
    },
    starterCode: {
      python: "answer = input('2 + 2 = ? ')\\nif answer == '4':\\n    print('Correct!')",
    },
  },
  {
    id: "lesson-2-2-8",
    moduleId: "module-2-2",
    order: 8,
    title: "Smart Calculator",
    type: "CHALLENGE",
    xpReward: 250,
    gemReward: 20,
    estimatedMin: 20,
    content: {
      type: "challenge",
      objective: "Pick an operation with if and calculate.",
      hint: "Use if/elif to choose the math.",
      successCondition: "hasPython:if",
    },
    starterCode: {
      python: "op = input('Choose + or -: ')\\nif op == '+':\\n    print(3 + 4)\\nelif op == '-':\\n    print(7 - 2)",
    },
  },
  {
    id: "lesson-2-2-9",
    moduleId: "module-2-2",
    order: 9,
    title: "My Decision Maker",
    type: "PROJECT",
    xpReward: 300,
    gemReward: 25,
    estimatedMin: 25,
    content: {
      type: "project",
      objective: "Build a small decision maker using if and elif.",
      hint: "Ask a question and give a response.",
      successCondition: "hasPython:if",
    },
    starterCode: {
      python: "choice = input('Left or right? ')\\nif choice == 'left':\\n    print('Go left')\\nelif choice == 'right':\\n    print('Go right')",
    },
  },
  {
    id: "lesson-2-3-1",
    moduleId: "module-2-3",
    order: 1,
    title: "Loops are Back",
    type: "STORY",
    xpReward: 100,
    gemReward: 5,
    estimatedMin: 10,
    content: {
      type: "story",
      objective: "Learn how for loops repeat work in Python.",
      hint: "for loops repeat a block of code.",
      successCondition: "hasPython:for",
    },
    starterCode: { python: "for i in range(3):\\n    print(i)" },
  },
  {
    id: "lesson-2-3-2",
    moduleId: "module-2-3",
    order: 2,
    title: "Count with For",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Use a for loop with range().",
      hint: "range(5) counts from 0 to 4.",
      successCondition: "hasPython:for",
    },
    starterCode: { python: "for i in range(5):\\n    print(i)" },
  },
  {
    id: "lesson-2-3-3",
    moduleId: "module-2-3",
    order: 3,
    title: "Loop Through Words",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Loop through letters in a word.",
      hint: "for letter in word:",
      successCondition: "hasPython:for",
    },
    starterCode: { python: "word = 'Nova'\\nfor letter in word:\\n    print(letter)" },
  },
  {
    id: "lesson-2-3-4",
    moduleId: "module-2-3",
    order: 4,
    title: "While it's True",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Use a while loop to repeat until a condition changes.",
      hint: "Remember to change the counter inside the loop.",
      successCondition: "hasPython:while",
    },
    starterCode: { python: "count = 3\\nwhile count > 0:\\n    print(count)\\n    count -= 1" },
  },
  {
    id: "lesson-2-3-5",
    moduleId: "module-2-3",
    order: 5,
    title: "The Countdown",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Create a countdown with while.",
      hint: "Subtract 1 each time.",
      successCondition: "hasPython:while",
    },
    starterCode: { python: "count = 5\\nwhile count > 0:\\n    print(count)\\n    count -= 1" },
  },
  {
    id: "lesson-2-3-6",
    moduleId: "module-2-3",
    order: 6,
    title: "Stop the Loop",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Use break and continue in a loop.",
      hint: "break exits the loop, continue skips to the next step.",
      successCondition: "hasPython:break|hasPython:continue",
    },
    starterCode: {
      python: "for i in range(5):\\n    if i == 2:\\n        continue\\n    if i == 4:\\n        break\\n    print(i)",
    },
  },
  {
    id: "lesson-2-3-7",
    moduleId: "module-2-3",
    order: 7,
    title: "The Times Table",
    type: "CHALLENGE",
    xpReward: 250,
    gemReward: 20,
    estimatedMin: 20,
    content: {
      type: "challenge",
      objective: "Print a small times table using for loops.",
      hint: "Loop over numbers and multiply.",
      successCondition: "hasPython:for",
    },
    starterCode: { python: "for i in range(1, 6):\\n    print(i * 3)" },
  },
  {
    id: "lesson-2-3-8",
    moduleId: "module-2-3",
    order: 8,
    title: "Guess the Number",
    type: "CHALLENGE",
    xpReward: 300,
    gemReward: 25,
    estimatedMin: 25,
    content: {
      type: "challenge",
      objective: "Use a while loop to keep guessing.",
      hint: "Repeat until the guess is correct.",
      successCondition: "hasPython:while",
    },
    starterCode: {
      python: "secret = '5'\\nguess = input('Guess: ')\\nwhile guess != secret:\\n    guess = input('Try again: ')\\nprint('Correct')",
    },
  },
  {
    id: "lesson-2-3-9",
    moduleId: "module-2-3",
    order: 9,
    title: "My Loop Machine",
    type: "PROJECT",
    xpReward: 350,
    gemReward: 30,
    estimatedMin: 25,
    content: {
      type: "project",
      objective: "Build a loop-based mini program.",
      hint: "Try for or while to repeat actions.",
      successCondition: "hasPython:for|hasPython:while",
    },
    starterCode: { python: "for i in range(3):\\n    print('Loop', i)" },
  },
  {
    id: "lesson-2-4-1",
    moduleId: "module-2-4",
    order: 1,
    title: "Lists are Like Bags",
    type: "STORY",
    xpReward: 100,
    gemReward: 5,
    estimatedMin: 10,
    content: {
      type: "story",
      objective: "Learn how lists store multiple items.",
      hint: "Lists use square brackets [].",
      successCondition: "hasPython:[]",
    },
    starterCode: { python: "items = []\\nprint(items)" },
  },
  {
    id: "lesson-2-4-2",
    moduleId: "module-2-4",
    order: 2,
    title: "Making a List",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Create a list and store it in a variable.",
      hint: "Try items = ['apple', 'banana']",
      successCondition: "hasPython:=",
    },
    starterCode: { python: "items = ['apple', 'banana']\\nprint(items)" },
  },
  {
    id: "lesson-2-4-3",
    moduleId: "module-2-4",
    order: 3,
    title: "Getting Items Out",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Read list items by index.",
      hint: "The first item is index 0.",
      successCondition: "hasPython:[0]|hasPython:[1]",
    },
    starterCode: { python: "items = ['a', 'b']\\nprint(items[0])\\nprint(items[1])" },
  },
  {
    id: "lesson-2-4-4",
    moduleId: "module-2-4",
    order: 4,
    title: "Adding to the List",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Add new items with append().",
      hint: "Use list.append('item').",
      successCondition: "hasPython:append",
    },
    starterCode: { python: "items = []\\nitems.append('apple')\\nprint(items)" },
  },
  {
    id: "lesson-2-4-5",
    moduleId: "module-2-4",
    order: 5,
    title: "How Long is it",
    type: "CODING",
    xpReward: 150,
    gemReward: 10,
    estimatedMin: 15,
    content: {
      type: "coding",
      objective: "Use len() to count list items.",
      hint: "len(list) returns a number.",
      successCondition: "hasPython:len",
    },
    starterCode: { python: "items = ['a', 'b', 'c']\\nprint(len(items))" },
  },
  {
    id: "lesson-2-4-6",
    moduleId: "module-2-4",
    order: 6,
    title: "Loop Through a List",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Use for loops with lists.",
      hint: "for item in items:",
      successCondition: "hasPython:for",
    },
    starterCode: { python: "items = ['a', 'b']\\nfor item in items:\\n    print(item)" },
  },
  {
    id: "lesson-2-4-7",
    moduleId: "module-2-4",
    order: 7,
    title: "The Shopping List",
    type: "CHALLENGE",
    xpReward: 250,
    gemReward: 20,
    estimatedMin: 20,
    content: {
      type: "challenge",
      objective: "Build a list using append().",
      hint: "Ask for items and append them.",
      successCondition: "hasPython:append",
    },
    starterCode: { python: "items = []\\nitems.append('bread')\\nprint(items)" },
  },
  {
    id: "lesson-2-4-8",
    moduleId: "module-2-4",
    order: 8,
    title: "Top Score Tracker",
    type: "CHALLENGE",
    xpReward: 300,
    gemReward: 25,
    estimatedMin: 25,
    content: {
      type: "challenge",
      objective: "Find the highest score from a list.",
      hint: "Use max() and len().",
      successCondition: "hasPython:append|hasPython:len|hasPython:max",
    },
    starterCode: { python: "scores = [3, 9, 4]\\nprint(max(scores))" },
  },
  {
    id: "lesson-2-4-9",
    moduleId: "module-2-4",
    order: 9,
    title: "My List Program",
    type: "PROJECT",
    xpReward: 350,
    gemReward: 30,
    estimatedMin: 25,
    content: {
      type: "project",
      objective: "Create a list-based mini program.",
      hint: "Append items and display the list.",
      successCondition: "hasPython:append",
    },
    starterCode: { python: "items = []\\nitems.append('Nova')\\nprint(items)" },
  },
  {
    id: "lesson-2-5-1",
    moduleId: "module-2-5",
    order: 1,
    title: "Your Python Journey",
    type: "STORY",
    xpReward: 100,
    gemReward: 5,
    estimatedMin: 10,
    content: {
      type: "story",
      objective: "Reflect on your Python journey with Nova.",
      hint: "Use print() to share your favorite moment.",
      successCondition: "hasPython:print",
    },
    starterCode: { python: "print('My favorite moment was loops.')" },
  },
  {
    id: "lesson-2-5-2",
    moduleId: "module-2-5",
    order: 2,
    title: "Design Your Program",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Plan your capstone program with input().",
      hint: "Ask the user for a choice.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "choice = input('Choose an adventure: ')\\nprint(choice)" },
  },
  {
    id: "lesson-2-5-3",
    moduleId: "module-2-5",
    order: 3,
    title: "Add Logic",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Add if logic to your capstone.",
      hint: "Use if to react to the choice.",
      successCondition: "hasPython:if",
    },
    starterCode: {
      python: "choice = input('Left or right? ')\\nif choice == 'left':\\n    print('Go left')",
    },
  },
  {
    id: "lesson-2-5-4",
    moduleId: "module-2-5",
    order: 4,
    title: "Add Loops",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Add a loop to repeat a part of your program.",
      hint: "Use for or while.",
      successCondition: "hasPython:for|hasPython:while",
    },
    starterCode: { python: "for i in range(3):\\n    print('Loop', i)" },
  },
  {
    id: "lesson-2-5-5",
    moduleId: "module-2-5",
    order: 5,
    title: "Add a List",
    type: "CODING",
    xpReward: 200,
    gemReward: 15,
    estimatedMin: 20,
    content: {
      type: "coding",
      objective: "Store options in a list.",
      hint: "Use [] and append().",
      successCondition: "hasPython:append|hasPython:[]",
    },
    starterCode: { python: "options = []\\noptions.append('go')\\nprint(options)" },
  },
  {
    id: "lesson-2-5-6",
    moduleId: "module-2-5",
    order: 6,
    title: "Nova's Final Challenge",
    type: "CHALLENGE",
    xpReward: 500,
    gemReward: 40,
    estimatedMin: 25,
    content: {
      type: "challenge",
      objective: "Combine input, logic, and loops.",
      hint: "Use input() to guide the loop.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "name = input('Name? ')\\nprint('Ready, ' + name)" },
  },
  {
    id: "lesson-2-5-7",
    moduleId: "module-2-5",
    order: 7,
    title: "Test Your Program",
    type: "PROJECT",
    xpReward: 300,
    gemReward: 25,
    estimatedMin: 25,
    content: {
      type: "project",
      objective: "Run your program and test it.",
      hint: "Use print() to show your results.",
      successCondition: "hasPython:print",
    },
    starterCode: { python: "print('Testing my program')" },
  },
  {
    id: "lesson-2-5-8",
    moduleId: "module-2-5",
    order: 8,
    title: "Polish and Share",
    type: "PROJECT",
    xpReward: 300,
    gemReward: 25,
    estimatedMin: 25,
    content: {
      type: "project",
      objective: "Make your program clear and friendly.",
      hint: "Use print() to guide the user.",
      successCondition: "hasPython:print",
    },
    starterCode: { python: "print('Welcome to my program')" },
  },
  {
    id: "lesson-2-5-9",
    moduleId: "module-2-5",
    order: 9,
    title: "The Builder's Masterwork",
    type: "PROJECT",
    xpReward: 600,
    gemReward: 60,
    estimatedMin: 30,
    content: {
      type: "project",
      objective: "Build your final capstone using everything you learned.",
      hint: "Use input() to make it interactive.",
      successCondition: "hasPython:input",
    },
    starterCode: { python: "name = input('Name? ')\\nprint('Builder', name)" },
  },
];

async function main() {
  await prisma.phase.upsert({
    where: { number: 2 },
    update: {},
    create: {
      id: "phase-2",
      number: 2,
      title: "Builder's Guild",
      kingdom: "Python Peaks",
      mentor: "Nova",
      ageMin: 8,
      ageMax: 11,
      colorHex: "#9D4EDD",
    },
  });

  const modules = [
    {
      id: "module-2-1",
      order: 1,
      title: "From Blocks to Python",
      description: "Bridge your block skills into real Python.",
      weeks: 2,
      skills: [
        "Python syntax",
        "Variables",
        "Print statements",
        "Block bridge",
        "Transition thinking",
      ],
    },
    {
      id: "module-2-2",
      order: 2,
      title: "Logic and Decisions",
      description: "Teach Python how to choose with if and else.",
      weeks: 2,
      skills: [
        "If statements",
        "Else",
        "Comparison operators",
        "Boolean logic",
        "Decision trees",
      ],
    },
    {
      id: "module-2-3",
      order: 3,
      title: "Loops in Python",
      description: "Repeat actions with for and while loops.",
      weeks: 2,
      skills: ["For loops", "While loops", "Range", "Loop control", "Iteration thinking"],
    },
    {
      id: "module-2-4",
      order: 4,
      title: "Lists and Collections",
      description: "Store and explore groups of values.",
      weeks: 2,
      skills: ["Lists", "Indexing", "Append", "Len", "Looping lists", "Collections thinking"],
    },
    {
      id: "module-2-5",
      order: 5,
      title: "Builder's Guild Capstone",
      description: "Combine all Phase 2 skills in a final project.",
      weeks: 2,
      skills: [
        "Project synthesis",
        "All Phase 2 concepts",
        "Creative coding",
        "Guild showcase",
        "Presentation",
      ],
    },
  ];

  for (const module of modules) {
    await prisma.module.upsert({
      where: { id: module.id },
      update: {
        title: module.title,
        description: module.description,
        order: module.order,
        weeks: module.weeks,
        skills: module.skills,
        phaseId: "phase-2",
      },
      create: {
        id: module.id,
        phaseId: "phase-2",
        order: module.order,
        title: module.title,
        description: module.description,
        weeks: module.weeks,
        skills: module.skills,
      },
    });
  }

  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { id: lesson.id },
      update: {
        moduleId: lesson.moduleId,
        order: lesson.order,
        title: lesson.title,
        type: lesson.type as never,
        content: lesson.content,
        xpReward: lesson.xpReward,
        gemReward: lesson.gemReward,
        estimatedMin: lesson.estimatedMin,
        starterCode: lesson.starterCode,
        solutionCode: Prisma.DbNull,
      },
      create: {
        id: lesson.id,
        moduleId: lesson.moduleId,
        order: lesson.order,
        title: lesson.title,
        type: lesson.type as never,
        content: lesson.content,
        xpReward: lesson.xpReward,
        gemReward: lesson.gemReward,
        estimatedMin: lesson.estimatedMin,
        starterCode: lesson.starterCode,
        solutionCode: Prisma.DbNull,
      },
    });
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
